// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjwwdktyzmpldfjfnehe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqd3dka3R5em1wbGRmamZuZWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTI1MDksImV4cCI6MjA2Mzg4ODUwOX0.WlRxZ6Hm2ylT_UaC2tiG6IfrYZR4KVfgg6B33_f5XXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);